"""
Anime Guild Request Board / Assassin Request Board Type Stubs

This file defines the interface for the request board system where:
- Guilds post tasks/requests with rewards
- Users can view available tasks
- Users can complete tasks and claim rewards
"""

from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum

class RequestStatus(Enum):
    """Status of a request"""
    OPEN: str
    IN_PROGRESS: str
    COMPLETED: str
    CANCELLED: str

class RequestType(Enum):
    """Types of requests available"""
    ASSASSINATION: str
    ESCORT: str
    RETRIEVAL: str
    EXPLORATION: str
    DEFENSE: str
    GATHERING: str
    OTHER: str

class RequestDifficulty(Enum):
    """Difficulty level of a request"""
    BEGINNER: str
    INTERMEDIATE: str
    ADVANCED: str
    LEGENDARY: str

class Reward:
    """Represents a reward for completing a request"""
    id: str
    gold: int
    experience: int
    items: List[Dict[str, Any]]
    description: str

    def __init__(self, gold: int, experience: int, items: Optional[List[Dict[str, Any]]] = None, description: str = "") -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...

class Request:
    """Represents a single request/task on the board"""
    id: str
    title: str
    description: str
    request_type: RequestType
    difficulty: RequestDifficulty
    status: RequestStatus
    reward: Reward
    posted_by: str
    posted_date: datetime
    deadline: Optional[datetime]
    accepted_by: Optional[str]
    completion_date: Optional[datetime]

    def __init__(
        self,
        title: str,
        description: str,
        request_type: RequestType,
        difficulty: RequestDifficulty,
        reward: Reward,
        posted_by: str,
        deadline: Optional[datetime] = None,
    ) -> None: ...

    def accept(self, user_id: str) -> bool: ...
    def complete(self) -> bool: ...
    def cancel(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...

class Guild:
    """Represents a guild that posts requests"""
    id: str
    name: str
    description: str
    members: List[str]
    created_date: datetime
    funds: int

    def __init__(self, name: str, description: str = "", initial_funds: int = 0) -> None: ...
    def add_member(self, user_id: str) -> bool: ...
    def remove_member(self, user_id: str) -> bool: ...
    def post_request(self, request: Request) -> bool: ...
    def fund_update(self, amount: int) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...

class User:
    """Represents a user/adventurer on the board"""
    id: str
    username: str
    level: int
    experience: int
    gold: int
    completed_requests: int
    guild_id: Optional[str]
    joined_date: datetime
    active_requests: List[str]
    declined_requests: List[str]

    def __init__(self, username: str, initial_gold: int = 100) -> None: ...
    def accept_request(self, request_id: str) -> bool: ...
    def complete_request(self, request_id: str) -> bool: ...
    def decline_request(self, request_id: str) -> bool: ...
    def gain_experience(self, amount: int) -> None: ...
    def gain_gold(self, amount: int) -> None: ...
    def join_guild(self, guild_id: str) -> bool: ...
    def level_up(self) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...

class RequestBoard:
    """Main request board that manages all requests"""
    requests: Dict[str, Request]
    users: Dict[str, User]
    guilds: Dict[str, Guild]

    def __init__(self) -> None: ...

    # Request management
    def post_request(self, guild_id: str, request: Request) -> bool: ...
    def get_all_requests(self) -> List[Request]: ...
    def get_open_requests(self) -> List[Request]: ...
    def get_requests_by_type(self, request_type: RequestType) -> List[Request]: ...
    def get_requests_by_difficulty(self, difficulty: RequestDifficulty) -> List[Request]: ...
    def get_request(self, request_id: str) -> Optional[Request]: ...
    def update_request_status(self, request_id: str, status: RequestStatus) -> bool: ...

    # User management
    def register_user(self, username: str) -> User: ...
    def get_user(self, user_id: str) -> Optional[User]: ...
    def get_user_by_username(self, username: str) -> Optional[User]: ...
    def update_user(self, user: User) -> bool: ...

    # Guild management
    def create_guild(self, name: str, description: str = "") -> Guild: ...
    def get_guild(self, guild_id: str) -> Optional[Guild]: ...
    def get_guild_requests(self, guild_id: str) -> List[Request]: ...

    # Actions
    def accept_request(self, user_id: str, request_id: str) -> bool: ...
    def decline_request(self, user_id: str, request_id: str) -> bool: ...
    def complete_request(self, user_id: str, request_id: str) -> bool: ...
    def get_user_active_requests(self, user_id: str) -> List[Request]: ...
    def get_user_declined_requests(self, user_id: str) -> List[Request]: ...
    def get_user_completed_requests(self, user_id: str) -> List[Request]: ...

    # Data persistence
    def save_state(self, filepath: str) -> bool: ...
    def load_state(self, filepath: str) -> bool: ...

class RequestBoardAPI:
    """Flask API wrapper for the request board"""
    board: RequestBoard

    def __init__(self, board: RequestBoard) -> None: ...

    # Request endpoints
    def get_all_requests(self) -> Dict[str, Any]: ...
    def get_request_by_id(self, request_id: str) -> Dict[str, Any]: ...
    def post_request(self, guild_id: str, request_data: Dict[str, Any]) -> Dict[str, Any]: ...
    def accept_request(self, user_id: str, request_id: str) -> Dict[str, Any]: ...
    def decline_request(self, user_id: str, request_id: str) -> Dict[str, Any]: ...
    def complete_request(self, user_id: str, request_id: str) -> Dict[str, Any]: ...

    # User endpoints
    def register_user(self, username: str) -> Dict[str, Any]: ...
    def get_user_profile(self, user_id: str) -> Dict[str, Any]: ...
    def get_user_requests(self, user_id: str) -> Dict[str, Any]: ...

    # Guild endpoints
    def create_guild(self, name: str, description: str) -> Dict[str, Any]: ...
    def get_guild(self, guild_id: str) -> Dict[str, Any]: ...
    def get_guild_requests(self, guild_id: str) -> Dict[str, Any]: ...
